target-version = "py38"

exclude = [".evergreen/csfle/bottle.py"]

[lint]
extend-select = [
  "B",        # flake8-bugbear
  "EXE",      # flake8-executable
  "F",        # pyflakes
  "FURB",     # refurb
  "I",        # isort
  "ICN",      # flake8-import-conventions
  "PGH",      # pygrep-hooks
  "PIE",      # flake8-pie
  "PL",       # pylint
  "PT",       # flake8-pytest-style
  "RET",      # flake8-return
  "RUF",      # Ruff-specific
  "UP",       # pyupgrade
  "YTT",      # flake8-2020
]
ignore = [
  "ISC001",   # Conflicts with formatter
  "PLR09",    # Too many <...>
  "PLR2004",  # Magic value used in comparison
  "UP008",    # Use `super()` instead of `super(__class__, self)`
  "ARG002",   # Unused method argument: `kwargs`
  "PTH123",   # `open()` should be replaced by `Path.open()`
  "B007",     # Loop control variable `canonname` not used within loop body"
  "UP031",    # Use format specifiers instead of percent format
  "PGH003",   # Use specific rule codes when ignoring type issues"
  "PLR1704",  # Redefining argument with the local name"
  "RUF012",   # Mutable class attributes should be annotated with `typing.ClassVar`
  "UP014",    # Convert `DownloadableComponent` from `NamedTuple` functional to class syntax"
  "RET503",   # Missing explicit `return` at the end of function able to return non-`None` value
  "E402",     # Module level import not at top of file
]
unfixable = ["F401"]

[lint.per-file-ignores]
".evergreen/ocsp/mock_ocsp_responder.py" = ["PLW"]
".evergreen/csfle/kms_*.py" = ["PLW"]
".evergreen/csfle/gcpkms/mock_server.py" = ["PLW"]